### PR TITLE
dev: Initialize skeleton code for app

### LINKED ISSUE #8: Add getting started guide
After the tech stack infra is done, add instructions for new developers to get started.

---

https://github.com/tianhaoz95/acumany-re/blob/d1f6aa7f0c89a4821062114a8783769b051f86a2/docs/README.md#L21-L26

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `todo` comment in d1f6aa7f0c89a4821062114a8783769b051f86a2 when #2 was merged. cc @tianhaoz95.

### LINKED ISSUE #26: Deciside which app framework to use
Deciside which app framework aligns better with the UI/UX design and the functionalities.

---

https://github.com/tianhaoz95/acumany-re/blob/657ef6944a61bc007d9399df54da83afe000edf5/docs/design-docs/tech-stack-study.md#L91-L95

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `todo` comment in 657ef6944a61bc007d9399df54da83afe000edf5. It&#x27;s been assigned to @tianhaoz95 because they committed the code.

### LINKED ISSUE #46: Implement barebone app infra
From the discussion in https://tianhaoz.com/acumany-re/#/design-docs/tech-stack-study, the conclusion so far is:

* Use Flutter/Dart for the app
* Use GraphQL for app-server communication
* Use Firebase as the vendor (we will need to change it later anyway)
* For now, design primary for mobile and then adapt to larger screen experience.

@ninjatron @tianhaoz95

### LINKED ISSUE #47: Add final decisions to tech stack docs with supporting arguments

### PR DESCRIPTION
**Pull request by tianhaoz95**
This PR checks in an initial Flutter demonstration app as-is together with some CI tests to set the infrastructure for future check-ins.

Things added:

- [x] Flutter app ( close #46 )
- [x] App unit tests
- [x] App integration tests
- [x] CI to run unit tests
- [x] CI to run integration tests
  - [x] iPad
  - [x] iPhone
  - [x] Android
- [x] CI to run build tests
- [x] Docs on getting started with the app ( close #8 )
- [x] Docs on what the CI pipelines are doing
- [x] Docs on the final decisions for the app ( close #26 #24 )
- [x] Docs on app

### CODE REVIEW

**Comment by tianhaoz95** [comment]
Whoops, Mergify is approving unwanted changes, need to fix that in the config.

**Comment by ninjatron** [comment]
Bro I don't know if all messages I am getting are from you or the bot. So I am being unresponsive since I don't know if something is auto generated or if you actually want me to look at something. Are all messages I receive from you? In any case, Flutter is going well. We should discuss initial features.

**Comment by tianhaoz95** [comment]
@ninjatron you can disable some of the notifications in https://github.com/settings/notifications to leave only when you are mentioned. You can also create filters in https://github.com/notifications like you would in gmail.

**Comment by tianhaoz95** [comment]
@ninjatron the app and corresponding docs and continuous integrations are ready. PTAL and leave a review if things look good.

Note: no need to manually merge the pull request as the bot will do it once all conditions are met.

**Pull request merged**
